In [2]:
"""
raid_ai_15k.py
==============
Extracts 15,000 AI-generated samples from RAID .jsonl files.
Uses 'machine_text' column as the AI-generated text.

Output CSV has exactly two columns:
  answers  → machine_text (AI-generated)
  label    → always 1
"""

import json
import os
import pandas as pd

AI_FILES = [
    "arxiv_davinci.jsonl",
    "arxiv_dolly.jsonl",
    "wikipedia_chatgpt.jsonl",
    "wikipedia_cohere.jsonl",
    "peerread_llama.jsonl",
    "wikipedia_davinci.jsonl"
    # add more if you have them
]



N_SAMPLES    = 15_000
MIN_WORDS    = 20
RANDOM_STATE = 42
OUTPUT_FILE  = "raid_ai_15k.csv"

# ── The key fix: always use 'machine_text' ────────────────────────
TEXT_COL = "machine_text"

def load_ai_files(file_list):
    all_texts = []

    for filepath in file_list:
        if not os.path.exists(filepath):
            print(f"  [SKIP] Not found: {filepath}")
            continue

        rows = []
        with open(filepath, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line:
                    rows.append(json.loads(line))

        if not rows:
            print(f"  [SKIP] Empty: {filepath}")
            continue

        if TEXT_COL not in rows[0]:
            print(f"  [WARN] '{TEXT_COL}' not found in {filepath}. Keys: {list(rows[0].keys())}")
            continue

        count = 0
        for row in rows:
            text = str(row.get(TEXT_COL, '')).strip()
            if text:
                all_texts.append(text)
                count += 1

        print(f"  [OK] {filepath}: {count} rows")

    return all_texts


if __name__ == '__main__':

    for f in AI_FILES:
        if os.path.exists(f):
            print(f"\nPeeking: {f}")
            with open(f, 'r') as fh:
                row = json.loads(fh.readline())
                print(f"  Keys: {list(row.keys())}")
                print(f"  machine_text sample: {str(row.get('machine_text',''))[:150]}")
            break

    print("\n" + "="*50)
    print("Loading machine_text from all files...")
    print("="*50)

    texts = load_ai_files(AI_FILES)
    print(f"\nTotal raw texts: {len(texts)}")

    df = pd.DataFrame({'answers': texts})

    df['answers'] = df['answers'].str.strip().str.lower()
    df = df.drop_duplicates(subset='answers')
    before = len(df)
    df = df[df['answers'].str.split().str.len() >= MIN_WORDS]
    print(f"After dedup + short-drop: {len(df)} rows  (removed {before - len(df)})")

    if len(df) < N_SAMPLES:
        print(f"WARNING: Only {len(df)} available. Using all.")
    else:
        df = df.sample(n=N_SAMPLES, random_state=RANDOM_STATE)
        print(f"Sampled exactly {N_SAMPLES} rows.")

    df['label'] = 1
    df = df[['answers', 'label']].reset_index(drop=True)

    print("\n" + "="*50)
    print(f"Shape       : {df.shape}")
    print(f"Label counts: {df['label'].value_counts().to_dict()}")
    print(f"\nSample rows:")
    print(df[['answers','label']].head(3).to_string())

    df.to_csv(OUTPUT_FILE, index=False)
    print(f"\nSaved: {OUTPUT_FILE}")

Peeking: arxiv_davinci.jsonl
  Keys: ['prompt', 'human_text', 'machine_text', 'model', 'source', 'source_ID']
  machine_text sample:
This paper studies the connection between ordinary Schroedinger quantum mechanics and a non-standard representation known as polymer quantum mechanic

==================================================
Loading machine_text from all files...
==================================================
  [OK] arxiv_davinci.jsonl: 3000 rows
  [OK] arxiv_dolly.jsonl: 3000 rows
  [OK] wikipedia_chatgpt.jsonl: 2995 rows
  [OK] wikipedia_cohere.jsonl: 2336 rows
  [OK] peerread_llama.jsonl: 586 rows
  [OK] wikipedia_davinci.jsonl: 3000 rows

Total raw texts: 14917
After dedup + short-drop: 14914 rows  (removed 2)
WARNING: Only 14914 available. Using all.

==================================================
Shape       : (14914, 2)
Label counts: {1: 14914}

Sample rows:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              answers  label
0                                                                                                                                                                                                                                                                                                                      this paper studies the connection between ordinary schroedinger quantum mechanics and a non-standard representation known as polymer quantum mechanics, which has become the focus of interest in recent years due to its potential links to planck scale physics. we first proceed in deducing polymer quantum mechanics from ordinary quantum mechanics by taking a particular limit, followed by a further consideration of the continuum limit, in which the process of going from the discrete to the schroedinger description is explored. resources are put into examining various relevant examples, such as the harmonic oscillator, a free particle and a simple cosmological model.      1
1                                                                    this work presents an analysis of the c2d spitzer legacy observations of the star-forming region of serpens. we propose criteria to distinguish genuine young stellar objects, ysos, from the contamination by extra-galactic sources. using these criteria, we record 286 ysos in total, 7.5% of which have been identified by previous infrared and x-ray studies. we further analyse the colors of the observed sources and compare them with those of theoretical star/disk/envelope models. objects that appear to be stars plus disks, to the extent of our observational capacity, demonstrate a diverse range of disk properties from active disks to passive disks and even debris disks. we also observe that the luminosity function of ysos in serpens extends at least to 0.001 lsun or lower for a 260-pc distance. additionally, we observe that less evolved ysos tend to be more clustered from a spatial correlation analysis.      1
2  the spectroscopic observations of ip ex hydrae in quiescence, which were carried out in 1991 and 2001, are reported. spin-modulated radial velocities, indicating a place of origin in the outer disc, were newly identified. the velocities were found to be in the range of ~500-600 km/s, corresponding to material revolving around the roche lobe radius. spin doppler tomograms also suggested accretion curtain emission extending from ~ 500-1000 km/s, verifying the predictions by the king & wynn (1999), belle et al. (2002), and norton et al. (2004) model. an overflow stream of matter falling onto the magnetosphere was also seen, as proposed in belle et al. (2005). moreover, the hbeta and hgamma spin radial velocities appear to be the consequence of the rotation of the funnel at the outer disc edge and the halpha velocities originated from a narrow and a broad-based component close to and far from the white dwarf, respectively, corresponding to the accretion curtain model.      1

Saved: raid_ai_15k.csv

In [6]:
# ── Extract human_text from same files ──────────────────────────

HUMAN_COL   = "human_text"
HUMAN_FILE  = "raid_human_15k.csv"

def load_human_files(file_list):
    all_texts = []

    for filepath in file_list:
        if not os.path.exists(filepath):
            print(f"  [SKIP] Not found: {filepath}")
            continue

        rows = []
        with open(filepath, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line:
                    try:
                        rows.append(json.loads(line))
                    except json.JSONDecodeError:
                        continue   # skip blank/corrupt lines

        if not rows:
            print(f"  [SKIP] Empty: {filepath}")
            continue

        if HUMAN_COL not in rows[0]:
            print(f"  [WARN] '{HUMAN_COL}' not in {filepath}. Keys: {list(rows[0].keys())}")
            continue

        count = 0
        for row in rows:
            text = str(row.get(HUMAN_COL, '')).strip()
            if text:
                all_texts.append(text)
                count += 1

        print(f"  [OK] {filepath}: {count} human rows")

    return all_texts

print("\n" + "="*50)
print("Extracting human_text from same files...")
print("="*50)

human_texts = load_human_files(AI_FILES)
print(f"\nTotal raw human texts: {len(human_texts)}")

df_human = pd.DataFrame({'answers': human_texts})
df_human['answers'] = df_human['answers'].str.strip().str.lower()
df_human = df_human.drop_duplicates(subset='answers')
before = len(df_human)
df_human = df_human[df_human['answers'].str.split().str.len() >= MIN_WORDS]
print(f"After dedup + short-drop: {len(df_human)} rows  (removed {before - len(df_human)})")

if len(df_human) < N_SAMPLES:
    print(f"WARNING: Only {len(df_human)} available. Using all.")
else:
    df_human = df_human.sample(n=N_SAMPLES, random_state=RANDOM_STATE)
    print(f"Sampled exactly {N_SAMPLES} rows.")

df_human['label'] = 0
df_human = df_human[['answers', 'label']].reset_index(drop=True)

print(f"Shape       : {df_human.shape}")
print(f"Label counts: {df_human['label'].value_counts().to_dict()}")
print(f"\nSample rows:")
print(df_human.head(3).to_string())

df_human.to_csv(HUMAN_FILE, index=False)
print(f"\nSaved: {HUMAN_FILE}")

==================================================
Extracting human_text from same files...
==================================================
  [OK] arxiv_davinci.jsonl: 3000 human rows
  [OK] arxiv_dolly.jsonl: 3000 human rows
  [OK] wikipedia_chatgpt.jsonl: 2995 human rows
  [OK] wikipedia_cohere.jsonl: 2336 human rows
  [OK] peerread_llama.jsonl: 586 human rows
  [OK] wikipedia_davinci.jsonl: 3000 human rows

Total raw human texts: 14917
After dedup + short-drop: 6584 rows  (removed 0)
WARNING: Only 6584 available. Using all.
Shape       : (6584, 2)
Label counts: {0: 6584}

Sample rows:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   answers  label
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   a rather non-standard quantum representation of the canonical commutation\nrelations of quantum mechanics systems, known as the polymer representation has\ngained some attention in recent years, due to its possible relation with planck\nscale physics. in particular, this approach has been followed in a symmetric\nsector of loop quantum gravity known as loop quantum cosmology. here we explore\ndifferent aspects of the relation between the ordinary schroedinger theory and\nthe polymer description. the paper has two parts. in the first one, we derive\nthe polymer quantum mechanics starting from the ordinary schroedinger theory\nand show that the polymer description arises as an appropriate limit. in the\nsecond part we consider the continuum limit of this theory, namely, the reverse\nprocess in which one starts from the discrete theory and tries to recover back\nthe ordinary schroedinger quantum mechanics. we consider several examples of\ninterest, including the harmonic oscillator, the free particle and a simple\ncosmological model.      0
1  we discuss the results from the combined irac and mips c2d spitzer legacy\nobservations of the serpens star-forming region. in particular we present a set\nof criteria for isolating bona fide young stellar objects, yso's, from the\nextensive background contamination by extra-galactic objects. we then discuss\nthe properties of the resulting high confidence set of yso's. we find 235 such\nobjects in the 0.85 deg^2 field that was covered with both irac and mips. an\nadditional set of 51 lower confidence yso's outside this area is identified\nfrom the mips data combined with 2mass photometry. we describe two sets of\nresults, color-color diagrams to compare our observed source properties with\nthose of theoretical models for star/disk/envelope systems and our own modeling\nof the subset of our objects that appear to be star+disks. these objects\nexhibit a very wide range of disk properties, from many that can be fit with\nactively accreting disks to some with both passive disks and even possibly\ndebris disks. we find that the luminosity function of yso's in serpens extends\ndown to at least a few x .001 lsun or lower for an assumed distance of 260 pc.\nthe lower limit may be set by our inability to distinguish yso's from\nextra-galactic sources more than by the lack of yso's at very low luminosities.\na spatial clustering analysis shows that the nominally less-evolved yso's are\nmore highly clustered than the later stages and that the background\nextra-galactic population can be fit by the same two-point correlation function\nas seen in other extra-galactic studies. we also present a table of matches\nbetween several previous infrared and x-ray studies of the serpens yso\npopulation and our spitzer data set.      0
2                                                                                                                                                                                                                                                  results from spectroscopic observations of the intermediate polar (ip) ex hya\nin quiescence during 1991 and 2001 are presented. spin-modulated radial\nvelocities consistent with an outer disc origin were detected for the first\ntime in an ip. the spin pulsation was modulated with velocities near ~500-600\nkm/s. these velocities are consistent with those of material circulating at the\nouter edge of the accretion disc, suggesting corotation of the accretion\ncurtain with material near the roche lobe radius. furthermore, spin doppler\ntomograms have revealed evidence of the accretion curtain emission extending\nfrom velocities of ~500 km/s to ~1000 km/s. these findings have confirmed the\ntheoretical model predictions of king & wynn (1999), belle et al. (2002) and\nnorton et al. (2004) for ex hya, which predict large accretion curtains that\nextend to a distance close to the roche lobe radius in this system. evidence\nfor overflow stream of material falling onto the magnetosphere was observed,\nconfirming the result of belle et al. (2005) that disc overflow in ex hya is\npresent during quiescence as well as outburst. it appears that the hbeta and\nhgamma spin radial velocities originated from the rotation of the funnel at the\nouter disc edge, while those of halpha were produced due to the flow of\nmaterial along the field lines far from the white dwarf (narrow component) and\nclose to the white dwarf (broad-base component), in agreement with the\naccretion curtain model.      0

Saved: raid_human_15k.csv

In [4]:
df=pd.read_csv("raid_ai_15k.csv")
df.head(6)

                                             answers  label
0  this paper studies the connection between ordi...      1
1  this work presents an analysis of the c2d spit...      1
2  the spectroscopic observations of ip ex hydrae...      1
3  this paper presents two classes of methods for...      1
4  thechromosphere of the sun is enigmatic and ha...      1
5  we explore the capability of detecting non-sta...      1

In [8]:
df_hum=pd.read_csv("raid_human_15k.csv")
df_hum.head(6)

                                             answers  label
0  a rather non-standard quantum representation o...      0
1  we discuss the results from the combined irac ...      0
2  results from spectroscopic observations of the...      0
3  we present lie group integrators for nonlinear...      0
4  the very nature of the solar chromosphere, its...      0
5  we analyze the possibility of probing non-stan...      0